# Generated by Django 5.2.5 on 2025-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='show_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_pagination',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menulink',
            name='show_search',
            field=models.BooleanField(default=True),
        ),
    ]
