# Generated by Django 5.2.5 on 2025-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_menulink_show_description_menulink_show_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=255)),
                ('show_header', models.BooleanField(default=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_menu', models.BooleanField(default=True)),
                ('show_description', models.BooleanField(default=True)),
                ('show_pagination', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
            },
        ),
        migrations.RemoveField(
            model_name='menulink',
            name='show_description',
        ),
        migrations.RemoveField(
            model_name='menulink',
            name='show_footer',
        ),
        migrations.RemoveField(
            model_name='menulink',
            name='show_header',
        ),
        migrations.RemoveField(
            model_name='menulink',
            name='show_menu',
        ),
        migrations.RemoveField(
            model_name='menulink',
            name='show_pagination',
        ),
        migrations.RemoveField(
            model_name='menulink',
            name='show_search',
        ),
    ]
